name: PHP Composer

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cache PHP extensions
              id: extcache
              uses: shivammathur/cache-extensions@v1
              with:
                  php-version: '8.4'
                  extensions: xdebug
                  key: php-extensions-v1

            - name: Restore PHP extensions cache
              uses: actions/cache@v5
              with:
                  path: ${{ steps.extcache.outputs.dir }}
                  key: ${{ steps.extcache.outputs.key }}
                  restore-keys: ${{ steps.extcache.outputs.key }}

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: xdebug

            - uses: actions/checkout@v7

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install

            - name: Composer audit
              run: composer audit

            - name: Run code style check
              run: ./vendor/bin/php-cs-fixer fix --dry-run

            - name: Run phpstan
              run: ./vendor/bin/phpstan

            - name: Run phpunit
              run: ./vendor/bin/phpunit

            - name: Install only prod dependencies
              run: composer install --no-dev --no-scripts --prefer-dist --optimize-autoloader

            - name: Check configs
              run: ./bin/console lint:yaml config --parse-tags --env=prod

            - name: Check container
              run: ./bin/console lint:container --env=prod

            - name: Prepare cache
              run: ./bin/console cache:warmup --env=prod

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v5
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-


    publish_latest:
        name: Publish latest image
        needs: build
        if: gitea.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout
                uses: actions/checkout@v7

            -   name: Setup QEMU
                uses: docker/setup-qemu-action@v4

            -   name: Cache Docker layers
                uses: actions/cache@v5
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ gitea.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-

            -   name: Publish tagged image
                uses: docker/build-push-action@v7
                with:
                    context: .
                    push: true
                    platforms: linux/arm64
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
                    tags: ${{ secrets.REGISTRY_HOST }}/${{ gitea.repository }}:latest
